require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/page_links", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PageLink. As you add validations to PageLink, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PageLink.create! valid_attributes
      get page_links_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      page_link = PageLink.create! valid_attributes
      get page_link_url(page_link)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_page_link_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      page_link = PageLink.create! valid_attributes
      get edit_page_link_url(page_link)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PageLink" do
        expect {
          post page_links_url, params: { page_link: valid_attributes }
        }.to change(PageLink, :count).by(1)
      end

      it "redirects to the created page_link" do
        post page_links_url, params: { page_link: valid_attributes }
        expect(response).to redirect_to(page_link_url(PageLink.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PageLink" do
        expect {
          post page_links_url, params: { page_link: invalid_attributes }
        }.to change(PageLink, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post page_links_url, params: { page_link: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested page_link" do
        page_link = PageLink.create! valid_attributes
        patch page_link_url(page_link), params: { page_link: new_attributes }
        page_link.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the page_link" do
        page_link = PageLink.create! valid_attributes
        patch page_link_url(page_link), params: { page_link: new_attributes }
        page_link.reload
        expect(response).to redirect_to(page_link_url(page_link))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        page_link = PageLink.create! valid_attributes
        patch page_link_url(page_link), params: { page_link: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested page_link" do
      page_link = PageLink.create! valid_attributes
      expect {
        delete page_link_url(page_link)
      }.to change(PageLink, :count).by(-1)
    end

    it "redirects to the page_links list" do
      page_link = PageLink.create! valid_attributes
      delete page_link_url(page_link)
      expect(response).to redirect_to(page_links_url)
    end
  end
end
